import type { Recipe } from '../recipes/types.js'
import type { WizardConfig } from '../types/config.js'
import { resolveEnvValue } from '../recipes/types.js'

export function renderEnv(recipes: Recipe[], config: WizardConfig): string {
  assertEnvSafe('TZ', config.tz)
  assertEnvSafe('PUID', String(config.puid))
  assertEnvSafe('PGID', String(config.pgid))
  assertEnvSafe('MEDIA_DIR', config.mediaDir)
  if (config.usenetDir) assertEnvSafe('USENET_DIR', config.usenetDir)
  if (config.torrentsDir) assertEnvSafe('TORRENTS_DIR', config.torrentsDir)

  const lines: string[] = [
    '# Generated by Hephaestus — do not edit manually',
    '',
    '# ── Shared ────────────────────────────────────────────────────────',
    `TZ=${config.tz}`,
    `PUID=${config.puid}`,
    `PGID=${config.pgid}`,
    `MEDIA_DIR=${config.mediaDir}`,
    config.usenetDir ? `USENET_DIR=${config.usenetDir}` : '# USENET_DIR=',
    config.torrentsDir ? `TORRENTS_DIR=${config.torrentsDir}` : '# TORRENTS_DIR=',
    '',
  ]

  for (const recipe of recipes) {
    if (recipe.envVars.length === 0) continue

    lines.push(`# ── ${recipe.name} ${'─'.repeat(Math.max(0, 64 - recipe.name.length))}`)
    for (const envVar of recipe.envVars) {
      const value = resolveEnvValue(envVar, config)
      assertEnvSafe(envVar.key, value)
      if (envVar.description) {
        lines.push(`# ${envVar.description}`)
      }
      lines.push(`${envVar.key}=${envVar.secret ? '' : value}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

export function renderGlobalEnv(config: WizardConfig): string {
  for (const [key, value] of Object.entries({
    BASE_DIR: config.baseDir,
    STACKS_DIR: config.stacksDir,
    MEDIA_DIR: config.mediaDir,
    USENET_DIR: config.usenetDir ?? '',
    TORRENTS_DIR: config.torrentsDir ?? '',
    TZ: config.tz,
    PUID: String(config.puid),
    PGID: String(config.pgid),
    HOST_IP: config.hostIp,
    DOMAIN: config.domain,
    DOCKER_SOCKET: config.dockerSocketPath,
    NAS_MOUNT: config.nasMountPath,
    RENDER_GID: String(config.renderGid),
  })) {
    assertEnvSafe(key, value)
  }

  return [
    '# _global.env — reference file for all stacks',
    '# Not loaded by Compose — copy vars to individual .env files as needed',
    '',
    `BASE_DIR=${config.baseDir}`,
    `STACKS_DIR=${config.stacksDir}`,
    `MEDIA_DIR=${config.mediaDir}`,
    config.usenetDir ? `USENET_DIR=${config.usenetDir}` : '# USENET_DIR=',
    config.torrentsDir ? `TORRENTS_DIR=${config.torrentsDir}` : '# TORRENTS_DIR=',
    `TZ=${config.tz}`,
    `PUID=${config.puid}`,
    `PGID=${config.pgid}`,
    `HOST_IP=${config.hostIp}`,
    config.domain ? `DOMAIN=${config.domain}` : '# DOMAIN=',
    `DOCKER_SOCKET=${config.dockerSocketPath}`,
    config.hasNas ? `NAS_MOUNT=${config.nasMountPath}` : '# NAS_MOUNT=',
    config.hasGpu ? `RENDER_GID=${config.renderGid}` : '# RENDER_GID=',
    '',
  ].join('\n')
}

export function assertEnvSafe(key: string, value: string): void {
  if (/[\r\n]/.test(value)) {
    throw new Error(`Unsafe env value for ${key}: values must not contain newlines`)
  }
}
