import type { Recipe } from '../recipes/types.js'
import type { WizardConfig } from '../types/config.js'
import { resolveEnvValue } from '../recipes/types.js'

export function renderEnv(recipes: Recipe[], config: WizardConfig): string {
  const lines: string[] = [
    '# Generated by Hephaestus — do not edit manually',
    '',
    '# ── Shared ────────────────────────────────────────────────────────',
    `TZ=${config.tz}`,
    `PUID=${config.puid}`,
    `PGID=${config.pgid}`,
    `MEDIA_DIR=${config.mediaDir}`,
    '',
  ]

  for (const recipe of recipes) {
    if (recipe.envVars.length === 0) continue

    lines.push(`# ── ${recipe.name} ${'─'.repeat(Math.max(0, 64 - recipe.name.length))}`)
    for (const envVar of recipe.envVars) {
      const value = resolveEnvValue(envVar, config)
      if (envVar.description) {
        lines.push(`# ${envVar.description}`)
      }
      lines.push(`${envVar.key}=${envVar.secret ? '' : value}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

export function renderGlobalEnv(config: WizardConfig): string {
  return [
    '# _global.env — reference file for all stacks',
    '# Not loaded by Compose — copy vars to individual .env files as needed',
    '',
    `BASE_DIR=${config.baseDir}`,
    `STACKS_DIR=${config.stacksDir}`,
    `MEDIA_DIR=${config.mediaDir}`,
    `TZ=${config.tz}`,
    `PUID=${config.puid}`,
    `PGID=${config.pgid}`,
    `HOST_IP=${config.hostIp}`,
    config.domain ? `DOMAIN=${config.domain}` : '# DOMAIN=',
    `DOCKER_SOCKET=${config.dockerSocketPath}`,
    config.hasNas ? `NAS_MOUNT=${config.nasMountPath}` : '# NAS_MOUNT=',
    config.hasGpu ? `RENDER_GID=${config.renderGid}` : '# RENDER_GID=',
    '',
  ].join('\n')
}
